---
- name: install and deploy apache2
  hosts: all
  become: True
  tasks:
    - name: Install packages
      apt:
        name: apache2
        state: latest
    - name: Start Apache server
      service:
        name: apache2
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/